name: Package Release Assets

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Authorize Mikroe Actions App
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.MIKROE_ACTIONS }}
          private-key: ${{ secrets.MIKROE_ACTIONS_KEY_AUTHORIZE }}

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Cache Python packages
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements/shared.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements/shared.txt
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Package and upload changed assets
        run: |
          python -u scripts/package.py "${{ steps.app-token.outputs.token }}" "${{ github.repository }}"